apiVersion: batch/v1
kind: Job
metadata:
  name: openhands-job-{{TASK_ID}}
spec:
  template:
    spec:
      containers:
        - name: openhands
          image: murphyalbert/cookbooks:openhandsrunnerlatest
          env:
            - name: TASK
              value: "{{TASK}}"
            - name: REPO_URL
              value: "{{REPO_URL}}"
            - name: MODEL
              value: "{{MODEL}}"
            - name: TASK_ID
              value: "{{TASK_ID}}"
            - name: GITHUB_TOKEN
              value: "{{GITHUB_TOKEN}}"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}
  backoffLimit: 1
