apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands-api
  template:
    metadata:
      labels:
        app: openhands-api
    spec:
      containers:
        - name: api
          image: murphyalbert/cookbooks:openhandsapilatest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "host.docker.internal"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: openhands-api
spec:
  selector:
    app: openhands-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080  # Pick a number between 30000–32767
  type: NodePort
